import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Appearance, FlatList, Modal, Pressable, SafeAreaView, StatusBar, StyleSheet, Text, TextInput, useColorScheme, View } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import { JournalEntry, ThemePreference } from './models/JournalEntry';
import { createEntry, deleteEntry, initializeJournal, loadEntries, updateEntry } from './services/journalService';
import { getSettings, saveSettings } from './services/settingsService';
import { displayDate, displayTime } from './utils/date';

type Screen='journal'|'search'|'settings';
export default function App() {
  const system=useColorScheme(); const [screen,setScreen]=useState<Screen>('journal'); const [folder,setFolder]=useState<string|null>(null); const [entries,setEntries]=useState<JournalEntry[]>([]); const [theme,setTheme]=useState<ThemePreference>('system'); const [loading,setLoading]=useState(true); const [draft,setDraft]=useState(''); const [saving,setSaving]=useState(false); const [editing,setEditing]=useState<JournalEntry|null>(null); const [editText,setEditText]=useState('');
  const dark=(theme==='system'?system:theme)==='dark'; const c=colors(dark);
  const refresh=async (root=folder) => { if(!root)return; try { setEntries(await loadEntries(root)); } catch(e) { Alert.alert('Could not read journal', e instanceof Error?e.message:'Try selecting your journal folder again.'); } };
  useEffect(()=>{(async()=>{ try { const s=await getSettings(); if(s?.folderUri){setFolder(s.folderUri);setTheme(s.theme);await refresh(s.folderUri);} } finally {setLoading(false);} })();},[]);
  const chooseFolder=async()=>{ try { const p=await FileSystem.StorageAccessFramework.requestDirectoryPermissionsAsync(); if(!p.granted) return; await initializeJournal(p.directoryUri); await saveSettings({folderUri:p.directoryUri,theme}); setFolder(p.directoryUri); await refresh(p.directoryUri); } catch(e) { Alert.alert('Could not set up journal',e instanceof Error?e.message:'Please try another folder.'); } };
  const save=async()=>{ if(!folder){await chooseFolder();return;} if(!draft.trim()){Alert.alert('Nothing to save','Write a thought before saving.');return;} setSaving(true);try{const e=await createEntry(folder,draft);setEntries(x=>[e,...x]);setDraft('');}catch(e){Alert.alert("Couldn't save your entry",e instanceof Error?e.message:'Your journal remains unchanged.');}finally{setSaving(false);}};
  const submitEdit=async()=>{if(!editing||!folder)return;try{const e=await updateEntry(folder,editing,editText);setEntries(x=>x.map(v=>v.id===e.id?e:v));setEditing(null);}catch(e){Alert.alert('Could not update entry',e instanceof Error?e.message:'Your journal remains unchanged.');}};
  const remove=(e:JournalEntry)=>Alert.alert('Delete this entry?','This permanently removes it from its Markdown file.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:async()=>{try{if(folder)await deleteEntry(folder,e);setEntries(x=>x.filter(v=>v.id!==e.id));}catch(err){Alert.alert('Could not delete entry',err instanceof Error?err.message:'Your journal remains unchanged.');}}}]);
  const setPreference=async(t:ThemePreference)=>{setTheme(t);if(folder)await saveSettings({folderUri:folder,theme:t});};
  const exportMarkdown=async()=>{ if(!folder)return; try { const output=`${FileSystem.cacheDirectory}MindLog-export.txt`; const summary=entries.map(e=>`# ${displayDate(e.createdAt)} · ${displayTime(e.createdAt)}\n\n${e.content}`).join('\n\n---\n\n'); await FileSystem.writeAsStringAsync(output,summary); await Sharing.shareAsync(output,{mimeType:'text/plain',dialogTitle:'Export MindLog journal'}); }catch(e){Alert.alert('Export failed',e instanceof Error?e.message:'Try again.');} };
  if(loading)return <View style={[styles.center,{backgroundColor:c.bg}]}><ActivityIndicator color={c.accent}/></View>;
  if(!folder)return <Onboarding c={c} choose={chooseFolder}/>;
  return <SafeAreaView style={[styles.safe,{backgroundColor:c.bg}]}><StatusBar barStyle={dark?'light-content':'dark-content'}/>{screen==='journal'&&<Journal c={c} draft={draft} setDraft={setDraft} save={save} saving={saving} entries={entries} onEdit={(e:JournalEntry)=>{setEditing(e);setEditText(e.content)}} onDelete={remove}/>} {screen==='search'&&<Search c={c} entries={entries} onEdit={(e:JournalEntry)=>{setEditing(e);setEditText(e.content)}} onDelete={remove}/>} {screen==='settings'&&<Settings c={c} folder={folder} theme={theme} setTheme={setPreference} choose={chooseFolder} exportJournal={exportMarkdown}/>}<Nav c={c} screen={screen} setScreen={setScreen}/><Modal visible={!!editing} animationType="slide" transparent><View style={styles.modalShade}><View style={[styles.modal,{backgroundColor:c.card}]}><Text style={[styles.modalTitle,{color:c.text}]}>Edit thought</Text><TextInput value={editText} onChangeText={setEditText} multiline autoFocus style={[styles.editor,{color:c.text,borderColor:c.line}]} placeholderTextColor={c.muted}/><View style={styles.actions}><Pressable onPress={()=>setEditing(null)}><Text style={{color:c.muted}}>Cancel</Text></Pressable><Pressable onPress={submitEdit}><Text style={{color:c.accent,fontWeight:'700'}}>Save changes</Text></Pressable></View></View></View></Modal></SafeAreaView>;
}
const Onboarding=({c,choose}:{c:any,choose:()=>void})=><SafeAreaView style={[styles.onboard,{backgroundColor:c.bg}]}><Text style={[styles.brand,{color:c.text}]}>MindLog</Text><Text style={[styles.tagline,{color:c.muted}]}>Your thoughts. Your timeline. Your device.</Text><View style={styles.grow}/><Text style={[styles.onTitle,{color:c.text}]}>Choose Journal Location</Text><Text style={[styles.copy,{color:c.muted}]}>MindLog stores Markdown files in a folder you control. No account, tracking, or cloud is required.</Text><Pressable style={[styles.primary,{backgroundColor:c.accent}]} onPress={choose}><Text style={styles.primaryText}>Choose journal folder</Text></Pressable><Text style={[styles.fine,{color:c.muted}]}>Recommended: Documents/MindLog</Text></SafeAreaView>;
const Journal=({c,draft,setDraft,save,saving,entries,onEdit,onDelete}:any)=><View style={styles.page}><Text style={[styles.brand,{color:c.text}]}>MindLog</Text><Text style={[styles.prompt,{color:c.text}]}>What’s on your mind?</Text><TextInput value={draft} onChangeText={setDraft} multiline placeholder="Write without overthinking…" placeholderTextColor={c.muted} style={[styles.composer,{color:c.text,backgroundColor:c.card,borderColor:c.line}]}/><Pressable disabled={saving} onPress={save} style={[styles.save,{backgroundColor:c.accent,opacity:saving?.6:1}]}><Text style={styles.primaryText}>{saving?'Saving…':'Save'}</Text></Pressable><Timeline c={c} entries={entries} onEdit={onEdit} onDelete={onDelete}/></View>;
const Timeline=({c,entries,onEdit,onDelete}:any)=> <FlatList data={entries} keyExtractor={(e:JournalEntry)=>e.id} contentContainerStyle={styles.timeline} ListEmptyComponent={<Text style={[styles.empty,{color:c.muted}]}>Your private timeline is ready. Capture your first thought above.</Text>} renderItem={({item})=><Entry c={c} entry={item} onEdit={onEdit} onDelete={onDelete}/>}/>;
const Entry=({c,entry,onEdit,onDelete}:any)=><Pressable onLongPress={()=>Alert.alert('Entry actions',undefined,[{text:'Edit',onPress:()=>onEdit(entry)},{text:'Delete',style:'destructive',onPress:()=>onDelete(entry)},{text:'Cancel',style:'cancel'}])} style={[styles.entry,{borderBottomColor:c.line}]}><Text style={[styles.entryDate,{color:c.muted}]}>{displayDate(entry.createdAt).toUpperCase()} · {displayTime(entry.createdAt)}</Text><Text style={[styles.content,{color:c.text}]}>{entry.content}</Text>{entry.updatedAt&&<Text style={[styles.edited,{color:c.muted}]}>Edited</Text>}</Pressable>;
const Search=({c,entries,onEdit,onDelete}:any)=>{const[q,setQ]=useState('');const found=useMemo(()=>entries.filter((e:JournalEntry)=>e.content.toLocaleLowerCase().includes(q.toLocaleLowerCase())),[q,entries]);return <View style={styles.page}><Text style={[styles.title,{color:c.text}]}>Search your thoughts</Text><TextInput autoFocus value={q} onChangeText={setQ} placeholder="Search…" placeholderTextColor={c.muted} style={[styles.search,{color:c.text,backgroundColor:c.card,borderColor:c.line}]}/><Timeline c={c} entries={q?found:[]} onEdit={onEdit} onDelete={onDelete}/></View>};
const Settings=({c,folder,theme,setTheme,choose,exportJournal}:any)=><View style={styles.page}><Text style={[styles.title,{color:c.text}]}>Settings</Text><Text style={[styles.section,{color:c.muted}]}>APPEARANCE</Text>{(['system','light','dark'] as ThemePreference[]).map(t=><Pressable key={t} style={styles.row} onPress={()=>setTheme(t)}><Text style={[styles.rowText,{color:c.text}]}>{theme===t?'◉':'○'}  {t[0].toUpperCase()+t.slice(1)}</Text></Pressable>)}<Text style={[styles.section,{color:c.muted}]}>JOURNAL STORAGE</Text><Text numberOfLines={1} style={[styles.path,{color:c.muted}]}>📁 {decodeURIComponent(folder)}</Text><Pressable onPress={choose}><Text style={{color:c.accent,fontWeight:'700'}}>Change folder</Text></Pressable><Text style={[styles.section,{color:c.muted}]}>DATA</Text><Pressable style={styles.row} onPress={exportJournal}><Text style={[styles.rowText,{color:c.text}]}>Export journal</Text><Text style={{color:c.muted}}>Markdown share file</Text></Pressable><Text style={[styles.section,{color:c.muted}]}>SYNC</Text><Text style={[styles.copy,{color:c.muted}]}>Google Drive and OneDrive are intentionally not connected in version 1. Your journal remains entirely on this device.</Text><Text style={[styles.section,{color:c.muted}]}>ABOUT</Text><Text style={[styles.rowText,{color:c.text}]}>MindLog 1.0.0</Text></View>;
const Nav=({c,screen,setScreen}:any)=><View style={[styles.nav,{backgroundColor:c.card,borderTopColor:c.line}]}>{([['journal','⌂','Journal'],['search','⌕','Search'],['settings','⚙','Settings']] as const).map(([id,icon,label])=><Pressable key={id} style={styles.navItem} onPress={()=>setScreen(id)}><Text style={{color:screen===id?c.accent:c.muted,fontSize:21}}>{icon}</Text><Text style={{color:screen===id?c.accent:c.muted,fontSize:11}}>{label}</Text></Pressable>)}</View>;
const colors=(dark:boolean)=>dark?{bg:'#101311',card:'#181d19',text:'#f1f4ef',muted:'#9ca59d',line:'#2d352f',accent:'#77b98a'}:{bg:'#fafbf8',card:'#ffffff',text:'#172019',muted:'#68736b',line:'#e3e8e3',accent:'#287542'};
const styles=StyleSheet.create({safe:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center'},page:{flex:1,paddingHorizontal:20,paddingTop:20},onboard:{flex:1,padding:28},brand:{fontSize:30,fontWeight:'700',letterSpacing:-1},tagline:{fontSize:17,marginTop:7},grow:{flex:1},onTitle:{fontSize:24,fontWeight:'700'},copy:{fontSize:15,lineHeight:22,marginTop:10},primary:{padding:16,borderRadius:12,alignItems:'center',marginTop:25},primaryText:{color:'white',fontWeight:'700',textTransform:'uppercase',letterSpacing:.6},fine:{fontSize:12,textAlign:'center',marginTop:13},prompt:{fontSize:18,fontWeight:'600',marginTop:24,marginBottom:10},composer:{minHeight:105,maxHeight:190,borderWidth:1,borderRadius:12,padding:14,fontSize:16,textAlignVertical:'top'},save:{alignSelf:'flex-end',marginTop:10,paddingVertical:11,paddingHorizontal:22,borderRadius:9},timeline:{paddingTop:20,paddingBottom:110},entry:{paddingVertical:18,borderBottomWidth:1},entryDate:{fontSize:12,fontWeight:'700',letterSpacing:.35},content:{fontSize:16,lineHeight:24,marginTop:8},edited:{fontSize:12,marginTop:8},empty:{paddingVertical:30,lineHeight:22,textAlign:'center'},title:{fontSize:28,fontWeight:'700',letterSpacing:-.5},search:{borderWidth:1,borderRadius:11,padding:13,fontSize:16,marginTop:18},section:{fontSize:12,fontWeight:'700',letterSpacing:1,marginTop:28,marginBottom:11},row:{paddingVertical:9,flexDirection:'row',justifyContent:'space-between'},rowText:{fontSize:16},path:{marginBottom:12,fontSize:13},nav:{height:64,borderTopWidth:1,flexDirection:'row',justifyContent:'space-around'},navItem:{flex:1,alignItems:'center',justifyContent:'center'},modalShade:{flex:1,backgroundColor:'#0008',justifyContent:'flex-end'},modal:{padding:22,borderTopLeftRadius:22,borderTopRightRadius:22},modalTitle:{fontSize:20,fontWeight:'700'},editor:{minHeight:150,borderWidth:1,borderRadius:10,padding:12,textAlignVertical:'top',fontSize:16,marginTop:16},actions:{flexDirection:'row',justifyContent:'space-between',marginTop:18}});
